spring.application.name=oauth2login

debug=true

spring.security.oauth2.client.registration.google.client-id=389684598131-7tomcetm98g6ujdlh9f02kbp6mln7ooc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=profile,email,https://www.googleapis.com/auth/contacts

logging.level.org.springframework.security=TRACE